### ISSUE TITLE
Wrong byte index for fam file

### ISSUE THREAD

**Issue by whtop** [lemieuxl/pyplink#3]
fam["byte"] = [
            int(np.ceil((1 + 1) / 4.0)) - 1 for i in range(len(fam))
        ]

Here, I think it should be 'np.ceil( i+1)' rather than 'np.ceil( 1 + 1)'

**Comment by lemieuxl** [comment]
I just checked, and both `fam["byte"]` and `fam["bit"]` are old pieces of code that should have been removed from the module. Since those variables are never used, they don't negatively impact the results. Good job finding this, though.

I will clean the code in a future release.
